// City to State mapping for India
export const cityToState = {
  "Mumbai": "Maharashtra",
  "Delhi": "Delhi",
  "Bangalore": "Karnataka",
  "Hyderabad": "Telangana",
  "Chennai": "Tamil Nadu",
  "Kolkata": "West Bengal",
  "Pune": "Maharashtra",
  "Ahmedabad": "Gujarat",
  "Jaipur": "Rajasthan",
  "Lucknow": "Uttar Pradesh",
  "Kanpur": "Uttar Pradesh",
  "Nagpur": "Maharashtra",
  "Indore": "Madhya Pradesh",
  "Bhopal": "Madhya Pradesh",
  "Patna": "Bihar",
  "Vadodara": "Gujarat",
  "Ghaziabad": "Uttar Pradesh",
  "Ludhiana": "Punjab",
  "Agra": "Uttar Pradesh",
  "Nashik": "Maharashtra",
  "Faridabad": "Haryana",
  "Meerut": "Uttar Pradesh",
  "Rajkot": "Gujarat",
  "Varanasi": "Uttar Pradesh",
  "Srinagar": "Jammu & Kashmir",
  "Aurangabad": "Maharashtra",
  "Dhanbad": "Jharkhand",
  "Amritsar": "Punjab",
  "Allahabad": "Uttar Pradesh",
  "Ranchi": "Jharkhand",
  "Gwalior": "Madhya Pradesh",
  "Jabalpur": "Madhya Pradesh",
  "Coimbatore": "Tamil Nadu",
  "Vijayawada": "Andhra Pradesh",
  "Jodhpur": "Rajasthan",
  "Madurai": "Tamil Nadu",
  "Raipur": "Chhattisgarh",
  "Kota": "Rajasthan",
  "Chandigarh": "Chandigarh",
  "Guwahati": "Assam",
  "Solapur": "Maharashtra",
  "Hubli": "Karnataka",
  "Mysore": "Karnataka",
  "Tiruchirappalli": "Tamil Nadu",
  "Bareilly": "Uttar Pradesh",
  "Aligarh": "Uttar Pradesh",
  "Tiruppur": "Tamil Nadu",
  "Gurgaon": "Haryana",
  "Moradabad": "Uttar Pradesh",
  "Jalandhar": "Punjab",
  "Noida": "Uttar Pradesh",
  "Gurugram": "Haryana",
  "Thane": "Maharashtra",
  "Bhiwandi": "Maharashtra",
  "Saharanpur": "Uttar Pradesh",
  "Gorakhpur": "Uttar Pradesh",
  "Siliguri": "West Bengal",
  "Aizawl": "Mizoram",
  "Ajmer": "Rajasthan",
  "Bikaner": "Rajasthan",
  "Saharanpur": "Uttar Pradesh",
  "Dehradun": "Uttarakhand",
  "Asansol": "West Bengal",
  "Nanded": "Maharashtra",
  "Rourkela": "Odisha",
  "Guntur": "Andhra Pradesh",
  "Jammu": "Jammu & Kashmir",
  "Ujjain": "Madhya Pradesh",
  "Mathura": "Uttar Pradesh",
  "Loni": "Uttar Pradesh",
  "Nellore": "Andhra Pradesh",
  "Jhansi": "Uttar Pradesh",
  "Bhilai": "Chhattisgarh",
  "Kolar": "Karnataka",
  "Ajmer": "Rajasthan",
  "Akola": "Maharashtra",
  "Bhilwara": "Madhya Pradesh",
  "Bikaner": "Rajasthan",
  "Shahjahanpur": "Uttar Pradesh",
  "Sitapur": "Uttar Pradesh",
  "Ratlam": "Madhya Pradesh",
  "Khammam": "Telangana",
  "Ongole": "Andhra Pradesh",
  "Bhopal": "Madhya Pradesh",
  "Karimnagar": "Telangana",
  "Nizamabad": "Telangana",
  "Rajahmundry": "Andhra Pradesh",
  "Tadepalligudem": "Andhra Pradesh",
  "Anantapur": "Andhra Pradesh",
  "Kadapa": "Andhra Pradesh",
  "Kurnool": "Andhra Pradesh",
  "Eluru": "Andhra Pradesh"
};

// All Indian States and Union Territories
export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar Islands",
  "Chandigarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Jammu & Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

// Top 50 Indian cities for autocomplete
export const topIndianCities = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune",
  "Ahmedabad", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal",
  "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad",
  "Meerut", "Rajkot", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar",
  "Allahabad", "Ranchi", "Gwalior", "Jabalpur", "Coimbatore", "Vijayawada", "Jodhpur",
  "Madurai", "Raipur", "Kota", "Chandigarh", "Guwahati", "Solapur", "Hubli", "Mysore",
  "Tiruchirappalli", "Bareilly", "Aligarh", "Tiruppur", "Gurgaon", "Moradabad", "Jalandhar",
  "Noida", "Gurugram", "Thane", "Bhiwandi", "Saharanpur", "Gorakhpur", "Siliguri"
];

// Get state from city
export const getStateFromCity = (city) => {
  return cityToState[city] || "";
};
